application: optout
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/optout.html
  upload: templates/optout.html
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /.*
  script: optout.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
